#!/bin/bash

_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "goodcat" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbmR5MTcwOS9jYXR1c2VyYm90" | base64 -d
    elif [[ $UPSTREAM_REPO == "badcat" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0ppc2FuMDkvY2F0dXNlcmJvdA==" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        echo "${UPSTREAM_REPO}"
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbmR5MTcwOS9jYXR1c2VyYm90" | base64 -d
    fi
}

_set_bot () {
    echo "  Downloading source code ..."
    if [[ $UPSTREAM_REPO_BRANCH ]]
    then
        git clone -b "${UPSTREAM_REPO_BRANCH}" $(_get_repolink)
    else
        git clone $(_get_repolink)
    fi
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    _run_catpack_git
    cd $CATPATH
    _run_cat_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "    Starting CatUserBot    "
    echo "
                        :'######:::::'###::::'########::::
                        '##... ##:::'## ##:::... ##..:::::
                         ##:::..:::'##:. ##::::: ##:::::::
                         ##:::::::'##:::. ##:::: ##:::::::
                         ##::::::: #########:::: ##:::::::
                         ##::: ##: ##.... ##:::: ##:::::::
                        . ######:: ##:::: ##:::: ##:::::::
                        :......:::..:::::..:::::..::::::::
    "

    echo "
    '##::::'##::'######::'########:'########::'########:::'#######::'########:
     ##:::: ##:'##... ##: ##.....:: ##.... ##: ##.... ##:'##.... ##:... ##..::
     ##:::: ##: ##:::..:: ##::::::: ##:::: ##: ##:::: ##: ##:::: ##:::: ##::::
     ##:::: ##:. ######:: ######::: ########:: ########:: ##:::: ##:::: ##::::
     ##:::: ##::..... ##: ##...:::: ##.. ##::: ##.... ##: ##:::: ##:::: ##::::
     ##:::: ##:'##::: ##: ##::::::: ##::. ##:: ##:::: ##: ##:::: ##:::: ##::::
    . #######::. ######:: ########: ##:::. ##: ########::. #######::::: ##::::
    :.......::::......:::........::..:::::..::........::::.......::::::..:::::
    "
    python3 -m userbot
}

_set_bot
